version: '3.8'

services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/tmp
      - /usr/src/app/log
    depends_on:
      - ${DB_HOST:-db}
      - redis
    tty: true
    stdin_open: true

  sidekiq:
    image: ${RAILS_API_IMAGE}
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - ${DB_HOST:-db}
      - redis
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  redis_data:
