version: '3.8'
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ${DB_VOLUME_PATH:-postgres_data}:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      BUNDLE_FROZEN: "false"
      BUNDLE_DEPLOYMENT: "false"
      BUNDLE_WITHOUT: ""
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/tmp
      - /usr/src/app/log
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local