version: '3.8'
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    environment:
      RAILS_ENV: production
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "${PORT:-80}:3000"
    volumes:
      - /usr/src/app/tmp
      - /usr/src/app/log
    depends_on:
      - db


volumes:
  postgres_data:
    driver: local