default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
